// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcq33n-mMqo5ooEElhtgDhQjKx7Wpwgys',
    appId: '1:505912934663:web:6d77691f8518e4431d45a2',
    messagingSenderId: '505912934663',
    projectId: 'veerpeercard-137b5',
    authDomain: 'veerpeercard-137b5.firebaseapp.com',
    storageBucket: 'veerpeercard-137b5.firebasestorage.app',
    measurementId: 'G-3JTP45HSVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvmAs7TAAT8R1UXFmgi1JW51mNqmh5eoE',
    appId: '1:505912934663:android:7c6fc549520eb1131d45a2',
    messagingSenderId: '505912934663',
    projectId: 'veerpeercard-137b5',
    storageBucket: 'veerpeercard-137b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNDR3hw6CBR6CVlCayAhvG47tJtfF-XCM',
    appId: '1:505912934663:ios:1b4db4cf593ccc5d1d45a2',
    messagingSenderId: '505912934663',
    projectId: 'veerpeercard-137b5',
    storageBucket: 'veerpeercard-137b5.firebasestorage.app',
    iosClientId: '505912934663-e1k75ukdqi3nhu5ue0btm5iv7g2jhjqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.veerpeercard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNDR3hw6CBR6CVlCayAhvG47tJtfF-XCM',
    appId: '1:505912934663:ios:1b4db4cf593ccc5d1d45a2',
    messagingSenderId: '505912934663',
    projectId: 'veerpeercard-137b5',
    storageBucket: 'veerpeercard-137b5.firebasestorage.app',
    iosClientId: '505912934663-e1k75ukdqi3nhu5ue0btm5iv7g2jhjqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.veerpeercard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcq33n-mMqo5ooEElhtgDhQjKx7Wpwgys',
    appId: '1:505912934663:web:ab019d44be1184dc1d45a2',
    messagingSenderId: '505912934663',
    projectId: 'veerpeercard-137b5',
    authDomain: 'veerpeercard-137b5.firebaseapp.com',
    storageBucket: 'veerpeercard-137b5.firebasestorage.app',
    measurementId: 'G-9JNRKV542T',
  );
}
